version: '3'

services:
  docsearch:
    build:
      context: .
      dockerfile: Dockerfile
    image: docsearch
    container_name: partybot-docsearch
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8000:80"