version: '3.7'

services:

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
    environment:
      - NODE_ENV=production